config/routes.rb
Rails.application.routes.draw do
  root :to =>  'home#index'

  devise_for :users, controllers: { registrations: "registrations"}
  resources :users do
    resources :contacts
  end
  resources :users  do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
    before_create :send_message
    belongs_to :user

  private

    def send_message
      begin
        response = RestClient::Request.new(
          :method => :post,
          :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
          :user => ENV['TWILIO_ACCOUNT_SID'],
          :password => ENV['TWILIO_AUTH_TOKEN'],
          :payload => { :Body => body,
                        :To => to,
                        :From => from }
        ).execute
      rescue RestClient::BadRequest => error
        message = JSON.parse(error.response)['message']
        errors.add(:base, message)
        throw(:abort)
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages
  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
  end



  def new
    @user = current_user
    @contact =@user.contacts.new
    respond_to do |format|
      format.html{}
      format.js
    end
  end

  def edit
    @user = current_user
    @contact = Contact.find(params[:id])
  end

  def create
    @user = current_user
    @contact = @user.contacts.new(contact_params)
    @contact.user = @user
    if @contact.save
      redirect_to user_path(@contact.user)
      respond_to do |format|
        format.html {redirect_to user_path(@contact.user)}
        format.js
      end
    else
      flash[:notice] = "no contact saved"
    end
  end

  def update
    @user = current_user
    @contact = Contact.find(params[:id])
    if @user.contacts.update(contact_params)
      redirect_to user_path(@contact.user), notice: 'contact was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    @user = current_user
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to user_path(@contact.user), notice: 'contact was successfully destroyed.'
  end


  private
    def contact_params
      params.require(:contact).permit(:name, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @user = current_user
    @message = @user.messages.new
    respond_to do |format|
      format.html{}
      format.js
    end
  end

  def create
    @user = current_user
    @message =@user.messages.new(message_params)
    @message.user = @user
    if @message.save
      redirect_to user_path(@message.user)
      respond_to do |format|
        format.html {redirect_to user_path(@message.user)}
        format.js
      end
    else
      render :new
    end
  end

  def destroy
    @user = current_user
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to user_path(@message.user)
    flash[:notice] = "Successfully deleted"
  end

  private

    def message_params
      params.require(:message).permit(:from, :to, :body)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
    def sign_up_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
  end

  def new

  end

  def create
    #code
  end

  def show
    @user = current_user
    @contacts = @user.contacts
    @messages = @user.messages
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_contacts.html.erb
<!DOCTYPE html>

<div class="container">
  <table align="center">
    <tr>
      <th class="th-name-column"><%= link_to "Name"%></th>
      <th class="th-phone-column"><%= link_to "PhoneNumber"%></th>
    </tr>
    <% for contact in @contacts do%>
    <tr>
      <td class="name-column"><%= contact.name%></td>
      <td class="phone-column"><%= contact.phone%> |<%= link_to "Edit", edit_user_contact_path(@user,contact) %> | <%= link_to "Delete", user_contact_path(@user, contact), :data => {:confirm => "Are you sure?", :method => "delete"} %>|<%= link_to "SMS"%> </td>
    </tr>
    <%end%>
  </table>
</div>

app/views/contacts/_form.html.erb
<!DOCTYPE html>
<div class="text-center">
  <%= render "layouts/errors", :object => @contact %>

    <%= form_for [@user,@contact], remote: true do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %><br/>
      <%= f.label :phone %>
      <%= f.text_field :phone %><br/>
      <%= f.submit %>
    <% end %>
</div>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

app/views/home/index.html.erb
<div class="container-fluid">
  <h1 class="twilioheading text-center">TWILIO SMS</h1><br/>
  <ul class="listdecorations text-center">
    <li><%= link_to "SignUp", new_user_registration_path, class:"btn"%></li><br/><br/>
    <li><%= link_to "LogIn", user_session_path, class:"btn"%></li>
  </ul>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors </h3>
  <ul>
    <% object.errors.full_messages.each do |message|%>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twilio</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Russo+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu+Mono" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="">
      <% if user_signed_in? %>
        <li class="listdecorations">
        <%= link_to('Logout', destroy_user_session_path, class:"btn", :method => :delete) %>
        </li>
      <% end %>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/messages/_errors.html.erb
<% if @message.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% @message.errors.messages[:base].each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/messages/_form.html.erb
<!DOCTYPE html>
<div class="text-center">
  <%= render "layouts/errors", :object => @message %>

    <%= form_for [@user,@message], remote: true do |f| %>
      <%= f.label :from %>
      <%= f.text_field :from %><br/><br/>
      <%= f.label :to %>
      <%= f.text_field :to %><br/><br/>
      <%= f.label :body %>
      <%= f.text_area :body, size: "24x6"%><br/>
      <%= f.submit "Send" %>
    <% end %>
</div>

app/views/messages/_messages.html.erb
<!DOCTYPE html>
<div class="container">
  <table align="center">
    <tr>
      <th class="text-center"><%= link_to "SMS"%></th>
    </tr>
    <% for message in @messages%>
      <tr>
        <td class="text-column">
        <p> To: <%= message.to %><br/> On: <%= message.created_at %> </p><br/>
        <p class = "trunq" > <span class="norm">Text:</span> <%= message.body %> </p></td>
      </tr>
    <%end%>
  </table>
</div>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

app/views/users/show.html.erb
<!DOCTYPE html>
<div class="container-fluid">
  Hello,<%= current_user.email%><hr/>

  <div class="row container">
    <div class="row">
      <%= render("/contacts/contacts")%><br/>
    </div>
    <div class="row text-center">
      <%= link_to "New Contact", new_user_contact_path(current_user), class:"btn"%>
    </div>
  </div><br/><br/>

  <div class="row container">
      <div class="row text-center">
      <%= render("/messages/messages")%>
    </div><br/>
    <div class="row text-center">
      <%= link_to "Send SMS", new_user_message_path(current_user), class:"btn"%>
    </div>
    </div>
</div>